dist: trusty
language: php
php:
  - 5.4
  - 5.6
  - hhvm
  - 7.0
install:
  - composer install --no-interaction --prefer-dist
script:
  - composer test
before_script:
  # Disable xdebug for speed.
  # NB: this should NOT be done for hhvm and php 7.0.
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" -a "$TRAVIS_PHP_VERSION" != "7.0" ]; then phpenv config-rm xdebug.ini; fi